window.FLIP = {
 "total": 38,
 "images": [
  "pages/split/p000.jpg",
  "pages/split/p001.jpg",
  "pages/split/p002.jpg",
  "pages/split/p003.jpg",
  "pages/split/p004.jpg",
  "pages/split/p005.jpg",
  "pages/split/p006.jpg",
  "pages/split/p007.jpg",
  "pages/split/p008.jpg",
  "pages/split/p009.jpg",
  "pages/split/p010.jpg",
  "pages/split/p011.jpg",
  "pages/split/p012.jpg",
  "pages/split/p013.jpg",
  "pages/split/p014.jpg",
  "pages/split/p015.jpg",
  "pages/split/p016.jpg",
  "pages/split/p017.jpg",
  "pages/split/p018.jpg",
  "pages/split/p019.jpg",
  "pages/split/p020.jpg",
  "pages/split/p021.jpg",
  "pages/split/p022.jpg",
  "pages/split/p023.jpg",
  "pages/split/p024.jpg",
  "pages/split/p025.jpg",
  "pages/split/p026.jpg",
  "pages/split/p027.jpg",
  "pages/split/p028.jpg",
  "pages/split/p029.jpg",
  "pages/split/p030.jpg",
  "pages/split/p031.jpg",
  "pages/split/p032.jpg",
  "pages/split/p033.jpg",
  "pages/split/p034.jpg",
  "pages/split/p035.jpg",
  "pages/split/p036.jpg",
  "pages/split/p037.jpg"
 ],
 "thumbs": [
  "pages/thumbs/tp000.jpg",
  "pages/thumbs/tp001.jpg",
  "pages/thumbs/tp002.jpg",
  "pages/thumbs/tp003.jpg",
  "pages/thumbs/tp004.jpg",
  "pages/thumbs/tp005.jpg",
  "pages/thumbs/tp006.jpg",
  "pages/thumbs/tp007.jpg",
  "pages/thumbs/tp008.jpg",
  "pages/thumbs/tp009.jpg",
  "pages/thumbs/tp010.jpg",
  "pages/thumbs/tp011.jpg",
  "pages/thumbs/tp012.jpg",
  "pages/thumbs/tp013.jpg",
  "pages/thumbs/tp014.jpg",
  "pages/thumbs/tp015.jpg",
  "pages/thumbs/tp016.jpg",
  "pages/thumbs/tp017.jpg",
  "pages/thumbs/tp018.jpg",
  "pages/thumbs/tp019.jpg",
  "pages/thumbs/tp020.jpg",
  "pages/thumbs/tp021.jpg",
  "pages/thumbs/tp022.jpg",
  "pages/thumbs/tp023.jpg",
  "pages/thumbs/tp024.jpg",
  "pages/thumbs/tp025.jpg",
  "pages/thumbs/tp026.jpg",
  "pages/thumbs/tp027.jpg",
  "pages/thumbs/tp028.jpg",
  "pages/thumbs/tp029.jpg",
  "pages/thumbs/tp030.jpg",
  "pages/thumbs/tp031.jpg",
  "pages/thumbs/tp032.jpg",
  "pages/thumbs/tp033.jpg",
  "pages/thumbs/tp034.jpg",
  "pages/thumbs/tp035.jpg",
  "pages/thumbs/tp036.jpg",
  "pages/thumbs/tp037.jpg"
 ],
 "toc": [],
 "meta": {
  "id": "bbq-grill",
  "cn": "GREENLINE BBQ 户外厨房目录册",
  "en": "GREENLINE BBQ & OUTDOOR KITCHEN CATALOG",
  "site": "furniture",
  "brand": "GREENLINE",
  "source": "F:\\目录册\\GREENLINE 2020  Catalogue- BBQ Grill & Outdoor Kitchen SHT系列.pdf2.pdf",
  "pdf_pages": 19,
  "flip_pages": 38,
  "dropped": []
 }
};
