window.FLIP = {
 "total": 57,
 "images": [
  "pages/full/p000.jpg",
  "pages/full/p001.jpg",
  "pages/full/p002.jpg",
  "pages/full/p003.jpg",
  "pages/full/p004.jpg",
  "pages/full/p005.jpg",
  "pages/full/p006.jpg",
  "pages/full/p007.jpg",
  "pages/full/p008.jpg",
  "pages/full/p009.jpg",
  "pages/full/p010.jpg",
  "pages/full/p011.jpg",
  "pages/full/p012.jpg",
  "pages/full/p013.jpg",
  "pages/full/p014.jpg",
  "pages/full/p015.jpg",
  "pages/full/p016.jpg",
  "pages/full/p017.jpg",
  "pages/full/p018.jpg",
  "pages/full/p019.jpg",
  "pages/full/p020.jpg",
  "pages/full/p021.jpg",
  "pages/full/p022.jpg",
  "pages/full/p023.jpg",
  "pages/full/p024.jpg",
  "pages/full/p025.jpg",
  "pages/full/p026.jpg",
  "pages/full/p027.jpg",
  "pages/full/p028.jpg",
  "pages/full/p029.jpg",
  "pages/full/p030.jpg",
  "pages/full/p031.jpg",
  "pages/full/p032.jpg",
  "pages/full/p033.jpg",
  "pages/full/p034.jpg",
  "pages/full/p035.jpg",
  "pages/full/p036.jpg",
  "pages/full/p037.jpg",
  "pages/full/p038.jpg",
  "pages/full/p039.jpg",
  "pages/full/p040.jpg",
  "pages/full/p041.jpg",
  "pages/full/p042.jpg",
  "pages/full/p043.jpg",
  "pages/full/p044.jpg",
  "pages/full/p045.jpg",
  "pages/full/p046.jpg",
  "pages/full/p047.jpg",
  "pages/full/p048.jpg",
  "pages/full/p049.jpg",
  "pages/full/p050.jpg",
  "pages/full/p051.jpg",
  "pages/full/p052.jpg",
  "pages/full/p053.jpg",
  "pages/full/p054.jpg",
  "pages/full/p055.jpg",
  "pages/full/p056.jpg"
 ],
 "thumbs": [
  "pages/thumbs_full/t000.jpg",
  "pages/thumbs_full/t001.jpg",
  "pages/thumbs_full/t002.jpg",
  "pages/thumbs_full/t003.jpg",
  "pages/thumbs_full/t004.jpg",
  "pages/thumbs_full/t005.jpg",
  "pages/thumbs_full/t006.jpg",
  "pages/thumbs_full/t007.jpg",
  "pages/thumbs_full/t008.jpg",
  "pages/thumbs_full/t009.jpg",
  "pages/thumbs_full/t010.jpg",
  "pages/thumbs_full/t011.jpg",
  "pages/thumbs_full/t012.jpg",
  "pages/thumbs_full/t013.jpg",
  "pages/thumbs_full/t014.jpg",
  "pages/thumbs_full/t015.jpg",
  "pages/thumbs_full/t016.jpg",
  "pages/thumbs_full/t017.jpg",
  "pages/thumbs_full/t018.jpg",
  "pages/thumbs_full/t019.jpg",
  "pages/thumbs_full/t020.jpg",
  "pages/thumbs_full/t021.jpg",
  "pages/thumbs_full/t022.jpg",
  "pages/thumbs_full/t023.jpg",
  "pages/thumbs_full/t024.jpg",
  "pages/thumbs_full/t025.jpg",
  "pages/thumbs_full/t026.jpg",
  "pages/thumbs_full/t027.jpg",
  "pages/thumbs_full/t028.jpg",
  "pages/thumbs_full/t029.jpg",
  "pages/thumbs_full/t030.jpg",
  "pages/thumbs_full/t031.jpg",
  "pages/thumbs_full/t032.jpg",
  "pages/thumbs_full/t033.jpg",
  "pages/thumbs_full/t034.jpg",
  "pages/thumbs_full/t035.jpg",
  "pages/thumbs_full/t036.jpg",
  "pages/thumbs_full/t037.jpg",
  "pages/thumbs_full/t038.jpg",
  "pages/thumbs_full/t039.jpg",
  "pages/thumbs_full/t040.jpg",
  "pages/thumbs_full/t041.jpg",
  "pages/thumbs_full/t042.jpg",
  "pages/thumbs_full/t043.jpg",
  "pages/thumbs_full/t044.jpg",
  "pages/thumbs_full/t045.jpg",
  "pages/thumbs_full/t046.jpg",
  "pages/thumbs_full/t047.jpg",
  "pages/thumbs_full/t048.jpg",
  "pages/thumbs_full/t049.jpg",
  "pages/thumbs_full/t050.jpg",
  "pages/thumbs_full/t051.jpg",
  "pages/thumbs_full/t052.jpg",
  "pages/thumbs_full/t053.jpg",
  "pages/thumbs_full/t054.jpg",
  "pages/thumbs_full/t055.jpg",
  "pages/thumbs_full/t056.jpg"
 ],
 "toc": [
  {
   "num": "01",
   "cn": "电视柜系列",
   "en": "TV Cabinet series",
   "items": [
    {
     "cn": "TV Cabinet 系列",
     "en": "TV Cabinet series",
     "page": 1
    }
   ]
  },
  {
   "num": "02",
   "cn": "酒柜系列",
   "en": "Wine Cabinet series",
   "items": [
    {
     "cn": "Wine Cabinet 系列",
     "en": "Wine Cabinet series",
     "page": 25
    }
   ]
  },
  {
   "num": "03",
   "cn": "背景墙系列",
   "en": "Background series",
   "items": [
    {
     "cn": "Background 系列",
     "en": "Background series",
     "page": 35
    }
   ]
  }
 ]
};
