window.FLIP = {
 "total": 24,
 "images": [
  "pages/full/p000.jpg",
  "pages/full/p001.jpg",
  "pages/full/p002.jpg",
  "pages/full/p003.jpg",
  "pages/full/p004.jpg",
  "pages/full/p005.jpg",
  "pages/full/p006.jpg",
  "pages/full/p007.jpg",
  "pages/full/p008.jpg",
  "pages/full/p009.jpg",
  "pages/full/p010.jpg",
  "pages/full/p011.jpg",
  "pages/full/p012.jpg",
  "pages/full/p013.jpg",
  "pages/full/p014.jpg",
  "pages/full/p015.jpg",
  "pages/full/p016.jpg",
  "pages/full/p017.jpg",
  "pages/full/p018.jpg",
  "pages/full/p019.jpg",
  "pages/full/p020.jpg",
  "pages/full/p021.jpg",
  "pages/full/p022.jpg",
  "pages/full/p023.jpg"
 ],
 "thumbs": [
  "pages/thumbs/tp000.jpg",
  "pages/thumbs/tp001.jpg",
  "pages/thumbs/tp002.jpg",
  "pages/thumbs/tp003.jpg",
  "pages/thumbs/tp004.jpg",
  "pages/thumbs/tp005.jpg",
  "pages/thumbs/tp006.jpg",
  "pages/thumbs/tp007.jpg",
  "pages/thumbs/tp008.jpg",
  "pages/thumbs/tp009.jpg",
  "pages/thumbs/tp010.jpg",
  "pages/thumbs/tp011.jpg",
  "pages/thumbs/tp012.jpg",
  "pages/thumbs/tp013.jpg",
  "pages/thumbs/tp014.jpg",
  "pages/thumbs/tp015.jpg",
  "pages/thumbs/tp016.jpg",
  "pages/thumbs/tp017.jpg",
  "pages/thumbs/tp018.jpg",
  "pages/thumbs/tp019.jpg",
  "pages/thumbs/tp020.jpg",
  "pages/thumbs/tp021.jpg",
  "pages/thumbs/tp022.jpg",
  "pages/thumbs/tp023.jpg"
 ],
 "toc": [],
 "meta": {
  "id": "weiding-consumable",
  "cn": "威思丁 客房易耗品目录册",
  "en": "WEIDING GUEST-ROOM CONSUMABLES",
  "site": "furniture",
  "brand": "威思丁",
  "source": "F:\\目录册\\2023年客房易耗品电子图册.pdf2.pdf",
  "pdf_pages": 24,
  "flip_pages": 24,
  "dropped": []
 }
};
